name = input("Enter your Name: ")
age = input("Enter your Age: ")
favorite_color = input("Enter your Favorite Color: ")
favorite_movie = input("Enter your Favorite Movie: ")
mobile_number = input("Enter your Mobile Number: ")
motto_in_life = input("Enter your Motto in Life: ")